extern void* calculateMain(void *null);
extern float completion;
extern bool done;
extern int indepCount;
extern int records;
extern char **names;
extern double **data;
extern double *actualValues;
extern double *min, *max, *step;
extern long int **best;
extern double keep;
extern double power;
